# Generated by Django 5.1.2 on 2024-11-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='fabric_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=100, verbose_name='season'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=4, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=100, verbose_name='style'),
        ),
    ]
