# Generated by Django 5.1.2 on 2024-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalog', '0002_product_color_product_fabric_type_product_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='brand'),
        ),
    ]
