# Generated by Django 5.1.2 on 2024-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalog', '0003_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=512, verbose_name='fabric_type'),
        ),
    ]
