# Generated by Django 5.1.2 on 2024-11-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='user',
            name='code_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='code_expires'),
        ),
    ]
