# Generated by Django 5.1.2 on 2024-11-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Заказ принят', max_length=50),
        ),
    ]
